name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Version
        run: node -v
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install
          run: npm install
        - name: Run tests
          run: npm test
  coveralls:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install
          run: npm install
        - name: Run Coverage
          run: npm run coverage
        - name: Coveralls GitHub Action
          uses: coverallsapp/github-action@v2.2.3
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            files: ./coverage/lcov.info
